# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34d6e3ef5e37b6f64078683e95942e29afd404368a326a1566ce00d4ea151fdf1c1b085fb29525045a00600e963105e4ad15332bd7f939efa461ece96c1f9be4

test:
  secret_key_base: 0d8fa3aed6d0546aeeccaa06cc0b0718ee18cd3c9f0676b460d46a25a065b3223814823b3ea00d20f9c1f91dbfb01c31406c552b517f7970a672f4d51d7ebd29

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
